app/src/main/java/com/odysee/app/MainActivity.java
app/src/main/java/com/odysee/app/adapter/CommentListAdapter.java
app/src/main/java/com/odysee/app/model/Claim.java
app/src/main/java/com/odysee/app/supplier/ReactToCommentSupplier.java
app/src/main/java/com/odysee/app/supplier/UnlockingTipsSupplier.java
app/src/main/java/com/odysee/app/supplier/WalletGetUnusedAddressSupplier.java
app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
app/src/main/java/com/odysee/app/ui/wallet/WalletFragment.java
app/src/main/java/com/odysee/app/utils/Lbry.java

Main thread -the rendering one- is blocked when Future.get() is called until a result is given by the Callable
This PR will use CompletableFuture on Android 7 and above and a slightly modified version of current one so main thread is no longer blocked.

Fix Future.get() blocking main thread

---

app/src/main/java/com/odysee/app/ui/wallet/WalletFragment.java

View more button on Wallet detail shows no content after navigating to other fragment and then returning to Wallet
Wallet Detail will show content

Fix View More on Wallet being empty

---

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java

A request is performed even when there are no comments.
Sometimes channel sign fails, making reaction.List request to also fail.
Comment reaction fetching and processing was blocking the UI thread
Comment reaktions aren't processed.
Signature is no longer sent for reaction.List when channel_sign had failed.
UI thread is no longer blocked.

Skip processing reactions when no comments and fix reactions fetching

---

app/src/main/java/com/odysee/app/ui/channel/ChannelCommentsFragment.java

Comments on the Comments section for Channels aren't shown
Now they are shown

Show comments on Channel fragment

---

app/src/main/java/com/odysee/app/adapter/ClaimListAdapter.java
app/src/main/java/com/odysee/app/ui/findcontent/SearchFragment.java

Performance when searching is slow. Results take a little bit too long to show on the results list
Results are now appearing a lot faster. It is also now searching for channels when it looks appropiate -when a single word is detected as the query string-

Boost search performance

---

app/src/main/java/com/odysee/app/MainActivity.java

Fix navigation item selected listener deprecation warning

---

app/src/main/java/com/odysee/app/callable/LighthouseSearch.java
app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java

Related content request is performed using an AsyncTask, which will leak views
The request is performed using a callable from a Future. This will not leak the progress bar view.

Use a callable to request related content

---

app/src/main/java/com/odysee/app/MainActivity.java
app/src/main/java/com/odysee/app/tasks/wallet/LoadSharedUserStateTask.java

The call to get preferences is throwing an exception because authentication token is not send along the request
This PR fixes that

Add authentication token to preferences_get call

---

app/src/main/java/com/odysee/app/callable/Search.java

Search results provided by Search callable class doesn't filter invalid reposts
Now results are filtered

Return filtered claims on Search callable

---

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java

Some factory classes had been deprecated on the ExoPlayer2 library. Code is still working, but will stop doing it at some time in the future.
Deprecated classes usage has been fixed with non-deprecated ones and some additional fixes for possible NullPointerexceptions on "context" has been added.

Refactor DataSourceFactory deprecated classes usage

---

app/src/main/java/com/odysee/app/callable/CommentEnabled.java

Response for comment list request returns an empty response string
Now the response is not empty

fix-comment-enabled

---

app/build.gradle
app/src/main/java/com/odysee/app/MainActivity.java
app/src/main/java/com/odysee/app/adapter/CommentListAdapter.java
app/src/main/java/com/odysee/app/callable/ChannelCreateUpdate.java
app/src/main/java/com/odysee/app/supplier/ClaimListSupplier.java
app/src/main/java/com/odysee/app/ui/BaseFragment.java
app/src/main/java/com/odysee/app/ui/channel/ChannelCommentsFragment.java
app/src/main/java/com/odysee/app/ui/channel/ChannelCreateDialogFragment.java
app/src/main/java/com/odysee/app/ui/channel/ChannelFormFragment.java
app/src/main/java/com/odysee/app/ui/channel/ChannelFragment.java
app/src/main/java/com/odysee/app/ui/channel/ChannelManagerFragment.java
app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
app/src/main/java/com/odysee/app/ui/publish/PublishFormFragment.java
app/src/main/java/com/odysee/app/ui/wallet/InvitesFragment.java
app/src/main/res/layout/card_invites_by_link.xml
app/src/main/res/layout/channel_form_bottom_sheet.xml
app/src/main/res/layout/container_comment_form.xml
app/src/main/res/layout/dialog_create_support.xml
app/src/main/res/layout/fragment_channel_form.xml
app/src/main/res/layout/fragment_publish_form.xml
app/src/main/res/values-v26/styles.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

Request user to sign in or create a channel when required

---

app/src/main/java/com/odysee/app/MainActivity.java
app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/settings.xml

Issue Number: No issue
No default speed setting
A setting for default speed

Add default speed setting

---

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
app/src/main/res/drawable/bg_seek.xml
app/src/main/res/drawable/ic_forward.xml
app/src/main/res/drawable/ic_rewind.xml
app/src/main/res/layout/fragment_file_view.xml

Issue Number: #114 
Need to tap on seek button.
Double tap to seek.
Add overlay to indicate seeking.

Implement double tapping to fast forward/rewind

---

app/src/main/res/layout-sw360dp/fragment_following.xml

Minimum height added formore precission on clicking -tip from Android Studio layout editor-

Fix buttons on filter layout on Following fragment being shifted to the left side

---

.github/workflows/ci.yml

Issue Number: Partially #158 since APKs are available in CI artifacts.
No CI on Pull Requests/Pushes
Added CI

Add GitHub Actions to build Full and Foss APKs

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/odysee/app/utils/LbryUri.java
app/src/test/java/com/odysee/app/utils/LbryUriTest.java

https://odysee.com links not handled.
https://odysee.com links open file viewer like other supported links.

Handle odysee.com links

---

app/build.gradle
app/src/main/java/com/odysee/app/MainActivity.java
app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java

This PR is also removing duplicated Lombok dependencies from build.gradle

Use ExoPlayer instead of deprecated SimpleExoPlayer

---

app/src/main/java/com/odysee/app/MainActivity.java
app/src/main/java/com/odysee/app/adapter/CommentItemDecoration.java
app/src/main/java/com/odysee/app/dialog/RepostClaimDialogFragment.java
app/src/main/java/com/odysee/app/ui/BaseFragment.java
app/src/main/java/com/odysee/app/ui/channel/ChannelCommentsFragment.java
app/src/main/java/com/odysee/app/ui/channel/ChannelCreateDialogFragment.java
app/src/main/java/com/odysee/app/ui/channel/ChannelFormFragment.java
app/src/main/java/com/odysee/app/ui/channel/ChannelFragment.java
app/src/main/java/com/odysee/app/ui/channel/ChannelManagerFragment.java
app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
app/src/main/java/com/odysee/app/ui/findcontent/FollowingFragment.java
app/src/main/java/com/odysee/app/ui/library/LibraryFragment.java
app/src/main/java/com/odysee/app/ui/library/PlaylistFragment.java
app/src/main/java/com/odysee/app/ui/publish/PublishFormFragment.java
app/src/main/java/com/odysee/app/ui/publish/PublishFragment.java
app/src/main/java/com/odysee/app/ui/publish/PublishesFragment.java
app/src/main/java/com/odysee/app/ui/verification/WalletVerificationFragment.java
app/src/main/java/com/odysee/app/ui/wallet/InvitesFragment.java
app/src/main/java/com/odysee/app/ui/wallet/RewardsFragment.java
app/src/main/java/com/odysee/app/ui/wallet/WalletFragment.java

Issue Number: #169
Sometimes snackbar is shown on the top of the screen
Snackbars are shown at the bottom, as expected

Show snackbars at the bottom of the screen

---

app/src/main/res/layout/fragment_all_content.xml

Simplify AllContent layout and increase interactive area

---

app/src/main/java/com/odysee/app/adapter/ClaimListAdapter.java
app/src/main/java/com/odysee/app/data/DatabaseHelper.java
app/src/main/java/com/odysee/app/model/Claim.java
app/src/main/java/com/odysee/app/model/ViewHistory.java
app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
app/src/main/java/com/odysee/app/utils/Helper.java
app/src/main/res/layout-sw360dp/list_item_stream.xml
app/src/main/res/layout/list_item_small_stream_horizontal.xml

Occasionally doesn't display the indicator and other times displays it
on not watched videos when scrolling through home page/search results.
Issue Number: #194 (partially)
No indicator on watched/partially watched videos
Red bar at bottom of thumbnail indicating playback position

Show playback progress indicator on thumbnail

---

.github/workflows/ci.yml

Branch was used for testing and no longer exists.

Remove gh-actions branch trigger from CI workflow

---

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java

When content has no comments, the Comments section is shown, but list is empty.
The form to add comments and a text indicating that there are no comments is shown.

Show No Comments section when appropiate

---

app/src/main/res/values/strings.xml

Issue Number: #232 (`"Use magic link" > "Use Magic Link via Email"`)

Change magic link sign in text

---

app/src/main/java/com/odysee/app/FirstRunActivity.java
app/src/main/java/com/odysee/app/MainActivity.java
app/src/main/java/com/odysee/app/OdyseeApp.java
app/src/main/java/com/odysee/app/YouTubeSyncActivity.java
app/src/main/java/com/odysee/app/ui/other/SettingsFragment.java
app/src/main/res/xml-v29/settings.xml

Issue Number: Partially #232
Light mode is set as default theme
System default mode is set as default theme

Use System Default as default app theme

---

app/build.gradle
app/src/main/java/com/odysee/app/GoLiveActivity.java

Possibly `app reloading after accepting permissions to camera/audio when trying to go live` from #232, error message in logcat changes but still occasionally crashes.
Use upstream version as it has JitPack build support.
Bump compile and target SDK version to 31 to be compatible with
HaishinKit.kt 0.9.4.

Bump HaishinKit.kt to 0.9.4

---

app/src/main/java/com/odysee/app/FirstRunActivity.java
app/src/main/java/com/odysee/app/GoLiveActivity.java
app/src/main/java/com/odysee/app/MainActivity.java
app/src/main/java/com/odysee/app/dialog/CreateSupportDialogFragment.java
app/src/main/java/com/odysee/app/dialog/RepostClaimDialogFragment.java
app/src/main/java/com/odysee/app/tasks/claim/ClaimListResultHandler.java
app/src/main/java/com/odysee/app/tasks/claim/ClaimListTask.java
app/src/main/java/com/odysee/app/tasks/claim/ResolveResultHandler.java
app/src/main/java/com/odysee/app/tasks/claim/ResolveTask.java
app/src/main/java/com/odysee/app/ui/channel/ChannelCommentsFragment.java
app/src/main/java/com/odysee/app/ui/channel/ChannelFragment.java
app/src/main/java/com/odysee/app/ui/channel/ChannelManagerFragment.java
app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
app/src/main/java/com/odysee/app/ui/findcontent/FollowingFragment.java
app/src/main/java/com/odysee/app/ui/findcontent/SearchFragment.java
app/src/main/java/com/odysee/app/ui/library/LibraryFragment.java
app/src/main/java/com/odysee/app/ui/library/PlaylistFragment.java
app/src/main/java/com/odysee/app/ui/publish/PublishFormFragment.java
app/src/main/java/com/odysee/app/ui/publish/PublishesFragment.java
app/src/main/java/com/odysee/app/ui/wallet/InvitesFragment.java
app/src/main/java/com/odysee/app/utils/Lbry.java
app/src/main/res/layout/fragment_publishes.xml
app/src/main/res/layout/popup_user.xml

Issue Number: #232
Points:
- `How do I get back to see my uploads?`
- `after publishing something, it went to a screen with "It looks like you have not published content to LBRY yet" with a New Publish button.`
No way to get back to list of publishes
After publishing nothing is shown due to ClaimListTask failing.
Menu button to show Publishes
Use Auth Token when listing claims in Publishes fragment.
Add ClaimListTask constructor that takes list of types and auth token.

Add Menu button to show Publishes, use Auth Token in Claim List

---

app/src/main/java/com/odysee/app/adapter/ClaimListAdapter.java

Issue Number: #232 (`Use Channel title if it exists, channel name if not.`)
Shows channel name
Show channel title if it exists, otherwise channel name

Use channel title on file claim preview

---

app/src/main/java/com/odysee/app/MainActivity.java
app/src/main/java/com/odysee/app/OdyseeApp.java
app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java

Some scheduled tasks were still using a new scheduled executor on FileViewFragment
They are now using the one created from OdyseeApp class.
For claims live-streaming, no reactions are being displayed currently. So app will no longer make a request in that case -I mean, the task is not scheduled-.

Use Application scheduled executor on FileViewFragment

---

app/src/main/java/com/odysee/app/adapter/ClaimListAdapter.java
app/src/main/res/values/strings.xml

Full view count number shown
Compacted number (12.3K for example) shown.

Use compact formatting for channel content claim view counts

---

.github/workflows/ci.yml

Issue Number: #284 
Unit tests not run on Push to master / Pull request
Possibility of bugs appearing from not noticing test failures
Unit tests run in CI

Run Unit Tests in CI

---

app/src/main/java/com/odysee/app/MainActivity.java
app/src/main/java/com/odysee/app/adapter/ChannelFilterListAdapter.java
app/src/main/java/com/odysee/app/adapter/ClaimListAdapter.java
app/src/main/java/com/odysee/app/adapter/CommentListAdapter.java
app/src/main/java/com/odysee/app/adapter/NotificationListAdapter.java
app/src/main/java/com/odysee/app/adapter/SuggestedChannelGridAdapter.java
app/src/main/java/com/odysee/app/adapter/YouTubeSyncItemAdapter.java
app/src/main/java/com/odysee/app/model/Claim.java
app/src/main/java/com/odysee/app/ui/channel/ChannelCommentsFragment.java
app/src/main/java/com/odysee/app/ui/channel/ChannelFormFragment.java
app/src/main/java/com/odysee/app/ui/channel/ChannelFragment.java
app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
app/src/main/java/com/odysee/app/ui/publish/PublishFormFragment.java
app/src/main/java/com/odysee/app/utils/ImageCDNUrl.java
app/src/main/java/com/odysee/app/utils/Utils.java

Issue Number: Partially #232
Using sizes extracted from Network tab after making requests to Odysee website
For channel profile pictures: 160 x 160 q = 85
For channel cover picture: 0 x 0, q = 95
For thumbnails pictures: 390 x 220, q = 85

Use odycdn CDN and change image files sizes

---

app/src/main/java/com/odysee/app/MainActivity.java
app/src/main/java/com/odysee/app/adapter/ClaimListAdapter.java
app/src/main/java/com/odysee/app/data/DatabaseHelper.java
app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
app/src/main/java/com/odysee/app/ui/library/LibraryFragment.java
app/src/main/java/com/odysee/app/ui/library/PlaylistFragment.java
app/src/main/res/menu/menu_stream.xml
app/src/main/res/values/strings.xml

- Playlists only display first 50.
- Cannot remove items from local playlists.
- Playlist claims loaded in pages of 50 (all at once), such that all claims shown.
- Ability to remove items from local playlists.

Playlist improvements

---

.github/workflows/ci.yml

CI failing due to wrong NDK version available.
Install correct NDK version before running Android build.

CI: Install NDK version 21.0.6113669

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/odysee/app/MainActivity.java

Fix: #316
Shared file not handled.
Publish Form opened with shared file.

Open Publish Form when receiving video file.

---

app/build.gradle

No functional change
No functional change
Needed for new clipboard behaviour in Android 13.
>

gradle: bump compileSdkVersion and targetSdkVersion to 33

---

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java

Skipping peer-review as this code doesn't do anything for the app

Remove informational message

---

app/src/main/java/com/odysee/app/MainActivity.java
app/src/main/java/com/odysee/app/ui/findcontent/AllContentFragment.java
app/src/main/java/com/odysee/app/utils/ContentSources.java
app/src/main/res/values/strings.xml

WILD_WEST category of content is no longer displayed
Now it is shown
There are other minor code changes here, also

Replace wildwest with rabbithole as category name

---

app/build.gradle

This upgrade could potentially fix a few memory leaks currently on logcat

Bump Glide to 4.13.2

---

app/src/full/java/com/odysee/app/utils/PlayerManager.java

Fix livestreams not playing or stopping after a few seconds

---

app/src/main/res/layout/fragment_publishes.xml

publishes: add contentDescription to floating button

---

app/src/main/java/com/odysee/app/tasks/wallet/SaveSharedUserStateTask.java
app/src/main/java/com/odysee/app/ui/channel/ChannelCommentsFragment.java
app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
app/src/main/java/com/odysee/app/ui/publish/GoLiveFormFragment.java
app/src/main/java/com/odysee/app/ui/publish/PublishFormFragment.java
app/src/main/java/com/odysee/app/ui/wallet/InvitesFragment.java

Set newly created channel as default when it is the only one on the account

---

app/src/main/java/com/odysee/app/MainActivity.java

Code is repeated on some conditional branching
There is no longer repeated code on there

Refactor an if-statement for notifications for API up to 23

---

app/src/main/java/com/odysee/app/ui/publish/GoLiveFormFragment.java

Check if activity is not null before initializing ReplaysPagerAdapter.
Also only load replays when actually on replays tab.
App crashes if quickly going back after going into GoLiveFormFragment.
Fix crash. Also only load replays when in publish replay tab.

go live form: fix crash when going back immediately after entering

---

app/src/main/java/com/odysee/app/ui/other/BlockedAndMutedFragment.java

Blocked channels are listed for each modChannel one at a time
Parallelize listing blocked channels for all modChannels at once (up to the limit of the thread pool)
@tzarebczan Can you please test if this makes loading blocked channels on Blocked & Muted faster? I believe you have some accounts with a lot of channels, right? You don't need to have any blocked channels, just see how long it takes for the loading indicator at the top right to disappear.

blocked & muted: load blocked channels in parallel

---

app/src/main/java/com/odysee/app/MainActivity.java
app/src/main/java/com/odysee/app/listener/DownloadActionListener.java
app/src/main/java/com/odysee/app/ui/channel/ChannelContentFragment.java
app/src/main/java/com/odysee/app/ui/findcontent/AllContentFragment.java
app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
app/src/main/java/com/odysee/app/ui/findcontent/FollowingFragment.java
app/src/main/java/com/odysee/app/ui/findcontent/SearchFragment.java
app/src/main/java/com/odysee/app/ui/library/LibraryFragment.java
app/src/main/java/com/odysee/app/ui/library/PlaylistFragment.java

chore(cleanup): remove DownloadActionListener

---

app/src/main/java/com/odysee/app/ui/channel/ChannelContentFragment.java
app/src/main/java/com/odysee/app/ui/findcontent/AllContentFragment.java
app/src/main/res/layout/fragment_all_content.xml
app/src/main/res/layout/fragment_channel_content.xml

Issue Number:
#406 (partial)
List pop ups
List is shown and then hidden if there are no items to be listed
This is also fixing the problem on the channet content

Smooth livestream's list displaying

---

app/src/main/res/layout/fragment_file_view.xml
app/src/main/res/values/strings.xml

Livechat tweaks

---

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java

By using the Handler from Looper, getting the activity and ensuring it is no null is no longer needed

Unindent some lines of code

---

app/src/main/java/com/odysee/app/OdyseeApp.java

Add javadoc to global executor getters methods

---

app/src/foss/java/com/odysee/app/utils/PlayerManager.java
app/src/full/java/com/odysee/app/utils/PlayerManager.java

Issue Number:
#444
Only an User Agent is sent.
A referer is also sent as a request header
In order to test this, On App Inspection tab, and Network, look for "mp4", click on any of them, and then on the new side section which opens, select Request tab.

Send odysee.com as referer for media player requests
