OdyseeTeam/odysee-android

app/build.gradle, app/src/main/java/com/odysee/app/ui/verification/ManualVerificationFragment.java
Issue Number:
It is needed to create a dummy file with fake values to allow Gradle to sync. These values are used to authenticate with Twitter API, which is not being used right now.
No need to create the file. Gradle won't be creating new resources to be merged into the app.
=> Disable Twitter verification code

app/src/main/java/com/odysee/app/ui/wallet/WalletFragment.java
Wallet detail is not shown when clicking the "View more" button
Now it is shown
=> Don't reset wallet detail items and adapter on start

app/src/main/java/com/odysee/app/adapter/CommentListAdapter.java, app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java, app/src/main/res/layout/fragment_file_view.xml
Comment list can only be expanded by clicking the Expand button
Now it will also expand when clicking on the single content when list is not expanded.
This PR is also refactoring some code to get the color for the reaction buttons
=> Expand to comment list when single comment is clicked

app/build.gradle, app/src/main/java/com/odysee/app/MainActivity.java, app/src/main/java/com/odysee/app/adapter/ClaimListAdapter.java, app/src/main/java/com/odysee/app/callable/Search.java, app/src/main/java/com/odysee/app/model/Claim.java, app/src/main/java/com/odysee/app/ui/channel/ChannelContentFragment.java, app/src/main/java/com/odysee/app/ui/channel/ChannelFragment.java, app/src/main/java/com/odysee/app/ui/channel/ChannelPlaylistsFragment.java, app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java, app/src/main/java/com/odysee/app/ui/findcontent/SearchFragment.java, app/src/main/java/com/odysee/app/utils/Lbry.java, app/src/main/res/drawable/ic_list_icon.xml, app/src/main/res/layout/fragment_channel_playlists.xml, app/src/main/res/layout/fragment_file_view.xml, app/src/main/res/layout/list_item_stream.xml, app/src/main/res/values-v28/styles.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
Playlists are not been shown.
Playlists items are shown on search results and on channel fragment. Then on single item view, playlist's items are listed instead of related content.
This PR also fixes a problem which caused bottom navigation bar to disappear after user tapped back from Search results.
Desugaring needs to be enabled in order to use Java Stream API on any Android API Level
=> Display collection type of claims and show items on Related section

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
The single comment area is shown for content there doesn't have any comments
The single comment are is no longer shown
=> Show single comment only when there is at least one to be shown

app/src/main/java/com/odysee/app/MainActivity.java
Notifications fragment is not closed when user clicks Search when Notifications are being shown
Notifications fragment is closed
=> Hide notifications when opening Search or Publish UI

app/src/main/java/com/odysee/app/adapter/CommentListAdapter.java, app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
After reacting to any comment, list collapses and it needs to be expanded again in order to view the reaction
After clicking on the reaction button, the request is performed, check for success done and amounts for that comment updated
There has been done some code changes on the comment list adapter for data set changes notifications.
=> Refresh comment reactions after reacting to it

app/src/main/java/com/odysee/app/supplier/ReactToCommentSupplier.java, app/src/main/java/com/odysee/app/tasks/BufferEventTask.java, app/src/main/java/com/odysee/app/tasks/CommentCreateTask.java, app/src/main/java/com/odysee/app/utils/Lbryio.java, app/src/main/java/com/odysee/app/utils/Lighthouse.java
ResponseBody could leak
ResponseBody is closed after getting the needed data from it. According to documentation, calling Response.body().string() would close it, but this ensures it will be certainly be closed
=> Close ResponseBody to avoid leaks

app/src/main/java/com/odysee/app/adapter/CommentListAdapter.java, app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
Replies aren't added to the RecyclerView after the reply has been posted to the remote server. Also, a few tweaks to make a better experience for the commenting part
Replies are displayed under their corresponding parent comment. The expanding and collapsing of the list is a little bit quicker and it also animates by itself.
=> Commentlist tweaks after commenting

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
Clicking on a related content item just reloads currently being played content
Related content now replaces the content which is currently being played
=> Related content no longer replaces current content

app/src/main/res/layout-sw360dp/list_item_stream.xml
"Reposted by" label sticks to the edge
The label is indented a little bit
=> Indent repost info section away from screen edge

app/src/main/java/com/odysee/app/MainActivity.java, app/src/main/java/com/odysee/app/ui/findcontent/FollowingFragment.java
Every time Following fragment is recreated, default -hidden- state Is used for the subscriptions list visibility
The state is stored and used when fragment is recreated, even when app was shutdown
=> Store subscriptions filter visibility state as a preference

app/src/main/java/com/odysee/app/adapter/NotificationListAdapter.java, app/src/main/java/com/odysee/app/data/DatabaseHelper.java, app/src/main/java/com/odysee/app/model/lbryinc/LbryNotification.java, app/src/main/java/com/odysee/app/tasks/lbryinc/NotificationListTask.java, app/src/main/res/layout/list_item_notification.xml
Channel picture -thumbnail- and content thumbnail are not shown on notification items
Channel picture is always shown for every notification item. When API responds with a thumbnail URL for the content, then that thumbnail is also shown
Database version has been updated.It has been tested that the update process is executed correctly.
About that update: a field has been renamed as it was semantically wrong -it was about the URL for the thumbnail, not the URL for the channel itself-; that requires to recreate the database, as a RENAME method for fields is not yet available for SQLite on Android.
The update renames current table to a temporary one, recreates the new table again, …
=> Show channel pictures and claim thumbnails on notifications

app/src/main/java/com/odysee/app/MainActivity.java, app/src/main/java/com/odysee/app/data/DatabaseHelper.java
Issue Number: #1
When user has signed out or its account has been removed, database tables are not cleared
All data is cleared when app sees that Odysee account has been removed from the device.
This is also fixing a problem which caused getting a blanck fragment when browsing to any fragment after swipping on the notification list and then closing it
=> Clear all database tables when user has signed out

app/src/main/AndroidManifest.xml, app/src/main/java/com/odysee/app/MainActivity.java, app/src/main/res/layout/activity_main.xml, app/src/main/res/values-v26/styles.xml, app/src/main/res/values-v31/styles.xml, app/src/main/res/values/styles.xml
When app starts, Android shows a white-ish or black-ish background as a preview to look like it is instantly starting, while in fact it is still creating the process and doing lots of other stuff before being able to draw. Then the app shows, in this case, the "splash screen"
Theme has been changed so it is showing the same background used by the "splash screen" and then it automatically .without any gap- transitions into the "splash screen".
On Android 12, there is no way to disable how Android shows the splash screen, which consists of a coloured background -taken from windowBackground- with app icon on top. My solution has been to not show our "splash screen" to avoid showing two of them to …
=> Show launcher drawable instead of blank background when cold starting

app/src/main/java/com/odysee/app/model/Claim.java
Thumbnails are no longer loading from vanwanet.com
thumbnails.odysee.com should be used instead
This is a one line change and it is also not making any functional change to the code, just pointing to a different server on the Internet, so I am no making any review request
=> Use thumbnails.odysee.com for thumbnails graphic files

app/src/main/java/com/odysee/app/MainActivity.java
Visibility is changed from the calling method thread. This thread is sometimes not the main thread, causing rendering issues after swiping on the Notifications fragment, i.e. new fragments being rendered blank.
When user wasn't logged in, the notifications empty list view was no longer shown after swiping to request new notifications.
Now visibility change is made explicitly from the main thread
=> Change visibility for views on the main thread

app/src/main/java/com/odysee/app/MainActivity.java
Authentication token is stored as a shared preference. This was used on the pre-alpha stage before switching to AccountManager API. This shared preference is not used anywhere else.
The authentication token is no longer stored as a shared preference.
Shared preference would still be stored after app is updated, so this PR is also removing it if found.
=> Remove auth_token from shared preferences

app/src/main/java/com/odysee/app/MainActivity.java, app/src/main/java/com/odysee/app/utils/Lbryio.java
Authentication token is stored on default shared preferences file
Token is no longer stored on shared preferences
=> Remove authentication token from default shared preferences

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
1. User clicks on a new content notification
2. Content is displayed
3. User clicks on a channel
4. Notification panel is shown without the AppBar
5. If user now clicks back, a weird layout appears showing the Home screen on the bottom half
Points 4 and 5 no longer happens and expected content is shown
=> Remove notification as source param when navigating to channel

app/src/main/java/com/odysee/app/MainActivity.java
When user clicks back on its device when consuming any playable claim, mini player is no longer visible. User needs to navigate to any other place, like switching to another tab, for example, in order to see the mini-player.
The player itself is reset every time user navigates to other place on the app.
Mini-player is now shown as expected and the player is no longer reset when a new fragment is shown.
=> Show mini-player after back key is pressed

app/src/main/java/com/odysee/app/utils/LbryUri.java, app/src/test/java/com/odysee/app/utils/LbryUriTest.java
LBRY.TV domain is no longer active, so conversion method from lory:// protocol to the domain is no  longer useful.
Test and method are gone.
=> Remove lbry protocol to lbry.tv url conversion method

app/src/main/java/com/odysee/app/MainActivity.java
When a new activity is started and user is playing some content, it is switched to picure-in-picture mode. When user then returns to the content by clicking on the PiP window, app screen is totally messed.
When app opens a new activity -like the Coming Soon or SignIn activities, for example- currently playing claim will be cleared from app state and player will also be stopped
After the merging PR for driving user to sign in when it is required, user will need to browse again to the content it was been played; it is better that than showing a bad UI when clicking the PiP window.
=> Stop player to avoid glitches after returning to app from PiP

app/build.gradle
OkHttp was logging an exception about Conscrypt not been available.
The exception is no longer logged. Also some threading problems are also potentially fixed. And built package size can also be a little bit smaller as some dependencies has been removed on latest OkHttp releases.
See [release notes](https://square.github.io/okhttp/changelog/#version-491). Original OkHttp version used by Odysee Android was 4.4.1.
There are a few newer versions there, but as they are still alpha, I think it is better to still keep using stable ones here.
=> Upgrade OkHttp to 4.9.1

app/src/main/java/com/odysee/app/utils/Lbry.java
For every **claim_search** call's returned item, a check for it to be a livestream is made when it has **no_source** set. That's making more network requests and clearly slowing the app because collections -playlists- cannot be a livestream, although they don't have a source set. For claims that don't have a source set, a network request is made to get the URL for the player.
Now collections are no longer checked to be a livestream.
=> Collections cannot be livestreams

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
Live streams aren't played due to 403 error returned by server
App sends a different Referer and now streams are working
=> Use bitwave as the livestream referer for media player

app/src/main/java/com/odysee/app/ui/findcontent/FollowingFragment.java
If "claim_search" request returns claims with a release time in the future -likely a scheduled livestream-, it will still be listed on the Following fragment, while app will be unable to play content, annoying the user.
Claims with a release time in the future is removed from the list even before any other processing, like sorting by its "live" status.
=> Remove claims with a future release time from Following fragment

app/src/main/java/com/odysee/app/model/Reactions.java, app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
This solves the issue `after commenting, own post has 1 fire, if you click fire again, it crashes.` noted in #91.
App crashes with a NPE when liking a comment that you yourself just made.
Fixes the crash so the NPE doesn't happen, by adding a null check and instantiation of the null field right before it's accessed.
I added a static convenience constructor for the `Reactions` class. If this makes sense then I can replace the other references to the plain constructor. No worries if you'd like to keep the plain constructor paradigm.
=> Fix NPE crash when liking a comment that you just made.

app/src/main/java/com/odysee/app/ui/findcontent/FollowingFragment.java
App is crashing for user when it is logged in and then opens the Following tab
App no longer crashes
=> Fix crash on Following fragment

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
Issue Number: #131
Related content no longer loads; resetting currently being played video instead
Related content is now loading, recycling current fragment.
Executor is also shutdown
=> Fix related content loading on same fragment reversion

app/src/main/java/com/odysee/app/SignInActivity.java
App crashes after adding new account
App is no longer crashing, account also stores authtentication token
=> Fix crash on samsung devices when adding new account

app/src/main/java/com/odysee/app/ui/wallet/WalletFragment.java
App will crash when user tries to open Wallet tab on a device made my Samsung
App is no longer crashing
=> Fix crash on Samsung devices when fetching transactions

app/src/main/AndroidManifest.xml
App is allowed to have a large memory heap. That was something left from original LBRY Android source code. It was using a daemon which downloaded blockchain headers, which could lead to too much memory to be used.
Odysee is not using lots of memory so it is safe to remove this attribute.
=> Remove legacy LBRY Android largeHeap attribute

app/src/main/java/com/odysee/app/MainActivity.java
Issue Number: #91
Activity layout will be corrupted when user tries to go to any section on the Profile menu while the notification list is being displayed
Notification list is hidden
=> Hide notifications when user goes to any item from the profile menu

app/src/main/java/com/odysee/app/MainActivity.java
Issue Number: #91
Odysee logo doesn0t provide any functionality
App will navigate to the Home tab when user taps on it
=> Navigate to Home tab when user taps on Odysee logo

app/src/main/java/com/odysee/app/adapter/ClaimListAdapter.java
Library tab will always appear as blank
Items are shown again
This was caused by my previous PR for filtering search results.
=> Fix all items being filtered out on Library tab

app/build.gradle, app/src/main/java/com/odysee/app/MainActivity.java, app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java, app/src/main/java/com/odysee/app/utils/Helper.java, app/src/main/res/layout/exo_playback_control_view.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/settings.xml
Issue Number: #113 
No quality selector
Quality selector next to the speed selector.
- An `Auto` selection to let Exoplayer decide the best quality to use (also for non-transcoded videos)
- Settings for default qualities on Wi-Fi or Mobile Data
| Player view | Settings |
|--|--|
| <img height="500" alt="Player view" src="https://user-images.githubusercontent.com/71804605/159434445-584f730a-167a-4932-92ec-3193563ec341.png"/> | <img height="500" alt="Settings" src="https://user-images.githubusercontent.com/71804605/159434603-d7dd05da-3a31-4f18-863f-714cd1efe120.png"/> |
The Exoplayer dependency is bumped to 2.16.0 to allow using the new track selection APIs. To the best of my knowledge this didn't …
=> Implement quality selection for transcoded videos

app/src/main/java/com/odysee/app/ui/findcontent/AllContentFragment.java
Issue Number: #91
Items on Odysee website for Wild West category don't match items on app
They match
=> Fix WildWest category request parameters

app/src/main/res/layout/fragment_file_view.xml
Issue Number: #118 
The video player has `fitsSystemWindows` set to true, which causes it to not overlap with the {back,home,apps} buttons and the status bar. However, when the status bar is not shown, the video will appear off center.
The video player is centered (and will be under the status bar when it is shown, which is expected).
=> Fix player not being centered in fullscreen mode

app/src/main/java/com/odysee/app/MainActivity.java
Clear All menu item is not removed when entering Search UI
Now it is removed and shown again when returning to Library tab page
=> Switch Clear All icon depending on Search UI

app/src/main/java/com/odysee/app/adapter/CommentListAdapter.java, app/src/main/res/layout/list_item_comment.xml
When collapsing parent for child's child comment, child's child remains visible, while direct childs are correctly colapsed
All childs are now collapsed
"View replies" vertical padding has been increased to avoid precission problem when clicking it.
DrawableCompat has been changed to Drawable as framework implementation is always better than AndroidX one.
=> Fix reply's indirect expanded childs collapsing issue

app/src/main/res/layout/channel_form_bottom_sheet.xml, app/src/main/res/layout/fragment_channel_form.xml
View is displayed at start of line
Position is now correct one
Some other changes has been done to improve area of clickable views
=> Fix CreditsBalanceView position on channel creator dialog

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
Issue Number: 177
The application crashes with an npe when comments will null reactions are also sorted while playing a video
No crash is observed while playing certain videos which triggered the crash
=> - Fix crash caused when sorting comments with no reactions

app/src/main/java/com/odysee/app/MainActivity.java, app/src/main/java/com/odysee/app/dialog/CreateSupportDialogFragment.java, app/src/main/java/com/odysee/app/dialog/RepostClaimDialogFragment.java, app/src/main/java/com/odysee/app/ui/channel/ChannelCommentsFragment.java, app/src/main/java/com/odysee/app/ui/channel/ChannelCreateDialogFragment.java, app/src/main/java/com/odysee/app/ui/channel/ChannelFormFragment.java, app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java, app/src/main/java/com/odysee/app/ui/findcontent/FollowingFragment.java, app/src/main/java/com/odysee/app/ui/publish/PublishFormFragment.java, app/src/main/java/com/odysee/app/ui/wallet/WalletFragment.java, app/src/main/java/com/odysee/app/utils/Lbry.java
Issue Number:
- Crashed occurred when fetching available and total wallet balances. This can be reproduced when navigating to the Wallet tab with no data connection on the device
- When in pip mode, if the "Allow picture-in-picture" setting is switched off and the app is launched, the video is resumed but neither the mini player nor the main player is shown (main player => Player in FileViewFragment)
- There was a flickering of an error text when you navigate to the Following tab if there was no data connection. 
- Added null checks when retrieving the wallet's available and total balances. Also prevented the wallet details from being updated if the wallet object is null
- Toggled the visibility …
=> Fixed some issues

app/src/main/res/layout-sw360dp/fragment_following.xml
On one of my test devices, the Discover link on Following fragment moves to the left. This was fixed on a previous commit, but after a device update, this is happenning again.
Link is again fixed to the right
=> A new fix for the Discover link shifting to the left on some devices

app/src/main/java/com/odysee/app/views/CreditsBalanceView.java, app/src/main/res/layout/card_wallet_balance.xml
When a CreditsBalanceView is displayed on the LayoutEditor, the credits icon is not shown, although space is reserved.
The icon is now shown
=> Show credits icon at design-time for CreditsBalanceView

app/src/main/java/com/odysee/app/ui/library/LibraryFragment.java
The clear all button is not shown on the Library fragment
The button is shown again
Fix regression caused by PR 179
=> Show the Clear All button on Library (regression fix)

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
Media is not being played because ExoPlayer cannot find an EXTM3U header
The EXTM3U header is not search for when content is not from an HLS media source. The correct Content-Type has been extracted from Wikipedia page [https://en.wikipedia.org/wiki/HTTP_Live_Streaming](https://en.wikipedia.org/wiki/HTTP_Live_Streaming)
=> Use correct Content-Type for transcoded HLS content

app/build.gradle, app/src/main/java/com/odysee/app/adapter/ClaimListAdapter.java, app/src/main/java/com/odysee/app/callable/Search.java, app/src/main/java/com/odysee/app/model/Claim.java, app/src/main/java/com/odysee/app/model/ClaimSearchCacheValue.java, app/src/main/java/com/odysee/app/model/Page.java, app/src/main/java/com/odysee/app/tasks/claim/ClaimSearchTask.java, app/src/main/java/com/odysee/app/ui/channel/ChannelContentFragment.java, app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java, app/src/main/java/com/odysee/app/ui/findcontent/FollowingFragment.java, app/src/main/java/com/odysee/app/ui/findcontent/SearchFragment.java, app/src/main/java/com/odysee/app/utils/Lbry.java, app/src/main/res/layout/fragment_search.xml, app/src/main/res/values/strings.xml
Fix: #186 
Fix a bug where `hasReachedEnd` was incorrectly set because the claims
array was smaller than `page_size` due to filtering.
LBRY page index starts at 1, there is no result at page 0.
- Use org.commonmark dependency and add extensions dependencies.
- Allow filtering for images and text in search.
- Put search file type list in scroll view.
=> Show images and markdown posts

app/src/main/java/com/odysee/app/MainActivity.java
Fix: #211
Default playback speed not used due to wrong key not getting value from preferences
Default playback speed used to set player speed
=> Fix wrong playback default speed preference key

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
Chat doesn't scroll when new items are added
Chat is always showing last fetched chat message
Handler wasn't working, so I replaced it with a scheduled executor which is only run a single time.
=> Use smooth scrolling when adding new chat messages on livestreams

app/src/main/java/com/odysee/app/utils/Lighthouse.java
Lighthouse is failing with timeouts errors when loading related content. Query is not being url-encoded
After increasing the timeout value, no error happens or is logged. query is now being url-encoded
=> Increase timeout amount for Lighthouse search queries

app/src/main/java/com/odysee/app/MainActivity.java, app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java, app/src/main/res/layout/fragment_file_view.xml
Issue Number: #217 
User gets confused as livestream doesn't seem to start
User is shown a message that stream is not currently live. User can still read and publish messages on the chat
Some nullity checking have been added, mostly to fix lint warnings.
The code for scroll to last chat message has been extracted because when user exits full-screen mode, app is no longer showing last message.
The openRewards() method has been finally removed as it was deprecated some time ago and no code was using it.
The getLivestreamUrl(JSONObject) method has been simplified. The API used to get if a channel had any live-streaming claim changed their key names while in development. That's why code was branching …
=> Show appropriate UI when a claim is for a non-live livestream

app/src/main/java/com/odysee/app/ui/channel/ChannelFragment.java
The count of tabs on Channel fragment wasn't updated after adding some new tabs, making the last one to not appear, happening this was the Comments tab.
Merging this directly.
=> Show Comments tab on Channel fragment

app/src/main/java/com/odysee/app/MainActivity.java, app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
App is crashing when exiting full screen mode for videos which are not livestreamed. Cause is smoothScrollingToLastmessage not checking for chat list adapter not being null
Null value is being checked to avoid crash. A few additional check for nullity has been added here and there.
=> Check for nullity

app/src/main/java/com/odysee/app/MainActivity.java, app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java, app/src/main/java/com/odysee/app/views/MediaRelativeLayout.java, app/src/main/res/anim/slide_in_bottom.xml, app/src/main/res/anim/slide_out_bottom.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/fragment_file_view.xml
Issue Number: #17
Quick snapping to/from the file view fragment.
Smooth slide in/out.
- Keep main_activity_other_fragment always visible so fragment is still
visible during transaction. This is fine as the fragment is removed at
the end of the transaction.
- Vertically stack fragment containers so main_activity_other_fragment
can be left visible. The main_activity_other_fragment container is
placed top-most so the animation is always visible.
- Use ?android:attr/colorBackground in FileViewFragment so it is not
transparent during the exit transition.
=> Animation when player minimized/maximized

app/src/main/java/com/odysee/app/model/lbryinc/Subscription.java, app/src/main/java/com/odysee/app/ui/channel/ChannelFragment.java, app/src/main/res/values/strings.xml
Issue Number: #232 (`notifications when following should not be turned on by default. confirm action on bell icon (turn on / off notifications)`)
Notifications are enabled by default when following a channel.
No confirmation when enabling/disabling channel notifications, only info message after.
Notifications are disabled by default when following a channel.
Confirmation before enabling/disabling channel notifications.
=> Following notifications: default off, show confirm change alert

app/src/main/res/layout/fragment_library.xml
Icon color is too dark when in dark mode
Use `?android:attr/textColorPrimary` for icon tint.
=> Fix dark mode icon color in Library

app/src/main/java/com/odysee/app/ui/channel/ChannelContentFragment.java
Issue Number: #232 (`can't infinite scroll to more pages on channel page`)
Channel content list stops after first 25 claims (or less if some are filtered).
At end of channel content list next page is loaded.
- Refactor claim list callables to return Page
- Individually parse result of each callable to get isLastPage value
from last callable (claim search).
=> Channel content: Set contentHasReachedEnd based on Page isLastPage

app/src/main/java/com/odysee/app/MainActivity.java
Issue Number: Partially #232 
When clicking on global player, content nothing happens
When clicked on global player, content is expanded
=> Fix global player not expanding to full content when clicked

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
Issue Number: #232 (`@richardharriscoaching channel - when you click on a playlist, it shows null (circle) x / x`)
"null • x/x" being shown when playing from non-local collections
Playlist title (or name if not available) shown
=> Set playlist title when playing from non-local collections

app/src/main/java/com/odysee/app/adapter/ClaimListAdapter.java, app/src/main/java/com/odysee/app/model/Claim.java, app/src/main/java/com/odysee/app/tasks/lbryinc/FetchStatCountTask.java, app/src/main/java/com/odysee/app/ui/channel/ChannelContentFragment.java, app/src/main/java/com/odysee/app/ui/channel/ChannelFragment.java, app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java, app/src/main/java/com/odysee/app/utils/Lbryio.java, app/src/main/res/layout-sw360dp/list_item_stream.xml
Issue Number: #232
- `Add channel profile thumbnail` (under `Claim previews` section)
- `add view counts to all videos (can batch the view api)` (under `Channel pages` section)
Only Publisher name and publish time shown
Publisher channel thumbnail shown, publish time moved below publisher name (same as on odysee.com)
(In channel page) view count shown next to publish time (separated by `•`)
=> Claim preview improvements

app/src/main/java/com/odysee/app/MainActivity.java, app/src/main/java/com/odysee/app/model/ClaimCacheKey.java, app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java, app/src/main/java/com/odysee/app/utils/Lbry.java
Fix regression from: https://github.com/OdyseeTeam/odysee-android/commit/dce3e8c0300f9633d223a0a828a428b9cddbb58f
Playback reloads ("Loading content" and spinner shown) when clicking on global player
Playback does not reload when clicking on global player
- Save canonicalUrl in claimCache.
- Cache claim even when not resolving a repost.
- Add FLAG_IMMUTABLE to createCurrentContentIntent to fix crash on
Android 12 when clicking global player.
=> Fix playback restarting when opening claim from global player

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java, app/src/main/res/layout/exo_playback_control_view.xml
- Move Quality and Speed selectors to top-right
- Hide Quality selector when only Auto is available
- Use bold text for Quality and Speed selectors
- Make duration views wrap_content width so progress bar can be wider
Issue Number: #232 (`Video player` section except last item about switching videos)
=> Rearrange layout of player controls

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java, app/src/main/res/values/strings.xml
Elapsed duration is still shown as it works properly.
Issue Number: #232 (`hide time elapsed / time remaining on livestreams (show otherwise)`)
Total time is shown and jumps in several second increments (what's buffered?)
"LIVE" is shown in place of total time
=> Only show "LIVE" for total duration on livestreams

app/src/main/java/com/odysee/app/model/Claim.java, app/src/main/java/com/odysee/app/ui/channel/ChannelContentFragment.java, app/src/main/java/com/odysee/app/ui/findcontent/FollowingFragment.java
Issue Number: #232 (`For the livestream content date - use the started at from livestream api (and not claim date)`)
Claim publish date used.
Date from `Start` field from Livestream API used.
=> Set Livestream claim release time to start time from API

app/src/main/java/com/odysee/app/adapter/ClaimListAdapter.java
Issue Number: #232 (`Following page - if you click Filter and then click on a channel, it stops showing active livestreams. If you click All, still doesn't show them. Need to leave and come back.`)
`addItems` checks that `items` is not empty when in the livestreams code path, so it will never add if the first claim is a livestream.
Remove `items` empty check in the livestreams code path, this is the same behaviour as in the other code path.
=> Following: Fix livestreams not being shown when filtering by channel

app/build.gradle, app/src/main/java/com/odysee/app/ui/channel/ChannelFragment.java, app/src/test/java/com/odysee/app/ui/channel/ChannelFragmentTest.java
Issue Number: #232 (`clicking Back from a playlist click takes you to channel page (should take you to playlist page?`)
After navigating back to channel page, it is always on first tab (Content).
Save tab that user was on and restore.
=> Save and switch back to previously shown fragment in channel page

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
- When buffer event happens, get player timeline window and compare
playback position with default (close to edge) position. If current
playback position is newer than default, set playback rate to 1x.
- Use setPlaybackSpeed() instead of setPlaybackParameters().
Note that this _can_ cause playback rate to reset if skipping to an area
that not loaded yet _and_ in front of the live edge. It shouldn't be a
major problem as when just watching at 2x to catch up on a livestream it
wouldn't go past the buffered area.
Issue Number: #232 (`If someone changes playback rate, and then it catches up to the live tip, change rate back to 1x (otherwise you continue to get buffering cause it's trying to play …
=> Set playback rate to 1x when livestream has reached live edge

app/src/main/java/com/odysee/app/adapter/ClaimListAdapter.java, app/src/main/java/com/odysee/app/tasks/lbryinc/FetchStatCountTask.java, app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java, app/src/main/res/values/strings.xml
i.e. on all places other than channel content.
Left slightly broken in #248
Due to 4dp `marginEnd`, publish time view is slightly indented.
Make view GONE so publish time view is not indented.
=> Set viewCountView visibility GONE when claim has no view count

app/build.gradle
Gradle fetches Google Cast library, although it is not needed at compile-time
The dependency has been disabled. This makes the app still compilable
The dependency has also been moved a few lines below. Previous lines are about the player or its codecs. The Cast dependency is different than that, although tightly related.
=> Disable Google Cast dependency while not implemented

app/src/main/java/com/odysee/app/MainActivity.java
Previously the app was built using SDK version 30. That required using '31' to refer to Android API Level S -Android 12-. Now that app is being built using sdk version 31, this trick is no longer needed.
This PR doesn't affect the app at all. Bypassing review request.
=> Use VERSION_CODES.S for Android 12

app/src/main/java/com/odysee/app/MainActivity.java, app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java, app/src/main/res/drawable/ic_play_arrow_shadow.xml, app/src/main/res/layout/fragment_file_view.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml-v29/settings.xml, app/src/main/res/xml/settings.xml
Add play icon (used instead of main action button) for manually starting
videos.
Issue Number: #232 (`When in miniplayer mode and navigating to another claim, it auto starts - should continue playing, and allow user to click play manually.`)
Playback autostarts when switching to another claim.
Old video keeps playing, new claim is rendered with a play icon and tapping the the media area starts playback.
=> Stop video autoplaying/stopping when switching to another claim

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
Fix quality selector not being shown on livestreams.
Issue Number: #232 (`missing quality options under Auto (confirmed stream had em)`)
No quality options on livestreams as it is not considered a transcoded stream
Hardcode that livestreams are transcoded so those that _are_ have quality selection, and those that don't just have a single quality.
=> Hardcode videoIsTranscoded = true on livestreams

app/src/main/java/com/odysee/app/MainActivity.java
Use nowPlayingClaim.getCanonicalUrl() if nowPlayingClaimUrl is null.
Tapping on media controls notification does nothing
Tapping on media controls notification opens player
=> Fix tapping on media controls notification not opening player

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
Only use timeline window edge logic when playing a livestream.
When playing at faster speed, then jumping back 10 seconds, playback speed resets to 1x.
Playback speed doesn't change
=> Fix playback speed resetting when jumping around

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
openFileClaim() sets "claim" param, so the `newClaim == null` code path,
which calls onNewClaim(), which sets `loadingNewClaim`, is not called.
When opening claims from Home tab, default speed and quality settings aren't used.
Default speed and quality settings used.
=> Fix default speed and quality ignored on claims from openFileClaim()

app/src/main/java/com/odysee/app/ui/channel/ChannelCreateDialogFragment.java
Call showError on MainActivity and dismiss dialog instead.
Regression in #196
When an error is shown in ChannelCreateDialogFragment app crashes due to infinite recursion
Snackbar properly shown and dialog dismissed.
=> Fix infinite recursion on ChannelCreateDialog showError method

app/build.gradle, app/src/main/res/xml-v29/settings.xml, app/src/main/res/xml/settings.xml
In dark mode, the drop down menus in App Settings have the same background color as the app, so it is hard to distinguish.
SimpleMenuPreference uses a gray background color.
|Before|After|
|--|--|
|<img src="https://user-images.githubusercontent.com/71804605/174704605-83de4785-bfae-464e-970e-cfe279b0b8ea.jpg">|<img src="https://user-images.githubusercontent.com/71804605/174704638-40cb4fa5-5b79-4b44-8a20-ede4939c0d84.jpg">|
=> Use SimpleMenuPreference library for better dark mode contrast

app/src/main/java/com/odysee/app/utils/Lbryio.java
When editing Lbryio.java file, an error is shown on String.join() method usage on API Level 25-
The error is no longer shown.
According to Android official site, String.join is no part of the desugaring, So this would make the app crash when trying to execute that method. However,after testing on Android 7 -API Level 24-, the app is not crashing and method is returning the expected comma-separated value.
Anyway, this PR is about removing that editing-time error. App is compiling without issues and running as expected both on current source code and with this PR applied.
=> Fix editing-time error about String.join()

app/src/main/java/com/odysee/app/utils/Lighthouse.java
This could lead to query string to be encoded twice
Double encoding is no longer possible
@ktprograms are you happy with this change?
=> Don't URL encode query on Lighthouse

app/build.gradle, app/src/main/java/com/odysee/app/adapter/ClaimListAdapter.java, app/src/main/java/com/odysee/app/adapter/CommentListAdapter.java, app/src/main/java/com/odysee/app/adapter/NotificationListAdapter.java, app/src/main/java/com/odysee/app/supplier/NotificationListSupplier.java, app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java, app/src/main/java/com/odysee/app/utils/FormatTime.java
- Add PrettyTime library (also used by NewPipe).
- Create FormatTime helper class.
- Use DateTimeFormatter to show absolute localized time in
FileViewFragment. There should be at least one place where the
absolute publish time is visible.
Issue Number: #232 (`check featured dates - some repost dates nothing coming through? see May 21, August 30, 2020, and "days ago" on various claims`)
Publish times further back than a month or two are shown as absolute date (e.g. `07 May 2020`)
Relative time shown no matter how far back publish time is.
Absolute time shown in FileViewFragment.
=> Show publish time as relative always, except on FileViewFragment

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java, app/src/main/java/com/odysee/app/ui/findcontent/FollowingFragment.java, app/src/main/java/com/odysee/app/utils/Lbryio.java
Issue Number:
Time to start or stop playing a livestream is broadcasted via the chat websocket. Currently, these data is not used
Livestream will be scheduled to start or stop being played at the expected time
To test this, I used the same code would be executed on the scheduled future, so it runs in a few minutes after running the app, to ensure I was able to get to some regular livestream. The livestream stop at the time I set. Once a start or stop event arrives, the same code would run and will provide same results.
=> Use start/stop events from chat websocket

app/src/main/java/com/odysee/app/MainActivity.java, app/src/main/res/values/strings.xml
- Add call to openFragment to openChannelUrl method.
Community Guidelines and Help & Support links are opened in a browser within the app
Community Guidelines and Help & Support links are opened in FileViewFragment/ChannelFragment
Note: this no longer goes to the "About" tab when opening Help & Support, if this is desired, I can add it. I am not adding it currently as it would require making the `currentTab` property in ChannelFragment `public`.
=> Open Community Guidelines and Help & Support links in-app

app/src/main/java/com/odysee/app/MainActivity.java, app/src/main/java/com/odysee/app/adapter/ProfileDefaultChannelAdapter.java, app/src/main/java/com/odysee/app/dialog/CreateSupportDialogFragment.java, app/src/main/java/com/odysee/app/ui/channel/ChannelCommentsFragment.java, app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java, app/src/main/java/com/odysee/app/ui/publish/PublishFormFragment.java, app/src/main/java/com/odysee/app/ui/wallet/InvitesFragment.java, app/src/main/java/com/odysee/app/utils/Helper.java, app/src/main/res/layout/list_item_profile_popup_channel.xml, app/src/main/res/layout/popup_user.xml, app/src/main/res/values/strings.xml
Issue Number: UI part for #230 
User cannot set a channel which app could select by default when one is needed
User is able to set a channel which will always be selected by default when commenting, tipping/supporting or publishing some content.
The default channel name is stored as user data. This means it is stored along the Android account. This will make it be deleted when user account is removed from the device. No longer having to make the cleanup when user signs out.
=> Allow to set a default channel used to interact with the platform

app/src/main/java/com/odysee/app/ui/channel/ChannelContentFragment.java
some channels with active livestreams aren't showing any on its content page
Active livestream is being listed
=> Remove duplicate livestream claim from regular claims on channel content

app/src/main/java/com/odysee/app/ui/findcontent/AllContentFragment.java, app/src/main/java/com/odysee/app/utils/ContentSources.java
- Use ContentSources v2 API.
- Use Wild West category from API including excludedChannelIds array.
- Refresh cache when locale changes.
Fix: #195
ContentSources cache does not refresh when changing locale
Wild West does not have any excluded channels
ContentSources cache refreshed when changing locale
Wild West uses excluded channels from API
=> ContentSources v2 API, Wild West excluded channels

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
Reset to original values if react fails.
Reaction button color and count only changes after react call completes, with no user feedback in the meantime.
Reaction button color and count changes immediately.
Resets to old value if react call fails.
=> Update Like/Dislike count/color immediately when reacting

app/build.gradle, app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java, app/src/main/java/com/odysee/app/utils/Helper.java
Required for fix in cast extension 2.17.0 to depend on up-to-date cast
library that creates PendingIntent correctly.
No change to user-facing behavior.
=> Bump ExoPlayer to 2.18.1

app/src/main/java/com/odysee/app/SignInActivity.java, app/src/main/java/com/odysee/app/ui/firstrun/SignInFragment.java, app/src/main/java/com/odysee/app/ui/verification/EmailVerificationFragment.java
When user tries to sign in, the email verification part of the process creates a new scheduled executor and in some cases a new executor
The process will be re-using the executors provided by the Application object
=> Use Application object executors when verifying email

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
Issue Number:
#303
App crashes when some claim result item is null while loading related content
No more crashing there
=> Fix a crash when loading related content with a null claim item on the results

app/src/main/java/com/odysee/app/ui/publish/PublishFormFragment.java, app/src/main/res/layout/channel_form_bottom_sheet.xml
Also make channel creation dialog name field single line.
- Crashes when creating (pressing "CREATE" button in creator dialog) when publishing.
- Channel name field in dialog is mulitline.
- Fix crash.
- Make name field single line.
=> Fix crash creating channel in publish form

app/src/main/java/com/odysee/app/MainActivity.java, app/src/main/java/com/odysee/app/ui/publish/PublishFormFragment.java, app/src/main/res/layout/app_bar_main.xml, app/src/main/res/layout/fragment_publish_form.xml
- Add TextView to custom app bar to display title. Built in title view
is placed below custom views so is not visible.
- Add regions to fragment_publish_form.xml to make sections of the form
easier to separate.
- Replace NestedScrollView -> ScrollView as it is not needed (the only
scrolling view, the tags view, is limited to 5 added + 8 suggested,
which doesn't need to scroll).
- Remove redundant LinearLayout from around Additional Options card
Titles in app bar are set but not visible.
Titles in app bar (set using `setActionBarTitle`) are displayed in TextView in custom app bar.
=> Fix app bar titles not showing, format fragment_publish_form.xml

app/src/main/java/com/odysee/app/adapter/ClaimListAdapter.java, app/src/main/java/com/odysee/app/ui/channel/ChannelManagerFragment.java, app/src/main/java/com/odysee/app/ui/publish/PublishesFragment.java
Hide edit action if pending claim selected. PublishForm doesn't seem to
handle getting the channel for a pending claim, so just disable edit.
Pending claims show "claim is pending publish" toast and can't be selected to delete.
Pending claims are selectable and can be clicked to toggle selection, but clicking the claim still shows "claim is pending publish" message.
Claim editing is disabled on pending claims.
=> Make it possible to delete pending claims

app/src/main/java/com/odysee/app/MainActivity.java, app/src/main/java/com/odysee/app/ui/channel/ChannelManagerFragment.java, app/src/main/java/com/odysee/app/ui/publish/PublishesFragment.java
Action bar title gets set by PublishForm and ChannelForm and stays set
when navigating back.
- Go to "Publishes"
- Long press on a claim and click edit
- Press back
- Title "Edit content" still visible in Publishes page
No title is shown after pressing back
=> Clear action bar title in Publishes and Channel Manager

app/src/main/java/com/odysee/app/ui/publish/PublishFormFragment.java
Use UTC_ZONE instead of repeating ZoneId.of("UTC") everywhere.
Date shown after picking is in wrong time zone due to date picker operating in UTC.
Date shown in correct time zone.
=> Fix time zone issues in Publish Form release date picker

app/src/main/java/com/odysee/app/callable/ChannelLiveStatus.java, app/src/main/java/com/odysee/app/ui/findcontent/AllContentFragment.java, app/src/main/java/com/odysee/app/ui/findcontent/FollowingFragment.java, app/src/main/res/layout/fragment_all_content.xml, app/src/main/res/values/strings.xml
Issue Number:
#313
No livestreams are listed for channels currently on a certain category
They are now shown
=> Show currently active livestreams for each category on the Home tab

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
Even in dark mode Markdown posts are rendered in light theme
In dark mode Markdown posts are rendered in dark theme
=> Support dark theme for Markdown posts

app/src/main/java/com/odysee/app/MainActivity.java
Fix `Lbry.ownClaims` being `null` because `ClaimListTask` failed without token
`fetchOwnClaims` fails so `Lbry.ownClaims` is `null`.
`fetchOwnClaims` fixed.
=> Pass token to ClaimListTask when fetching own claims

app/src/main/java/com/odysee/app/ui/publish/PublishFormFragment.java, app/src/main/res/values-af/strings.xml, app/src/main/res/values-ca/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-et/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-gu/strings.xml, app/src/main/res/values-he/strings.xml, app/src/main/res/values-hi/strings.xml, app/src/main/res/values-id/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-jv/strings.xml, app/src/main/res/values-ms/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ro/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sr/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values-vi/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
Fix warnings with deposit amount code.
When editing, the form's action bar title is "Edit content"
Title is "Edit upload" (in contrast to "Edit livestream" used when editing livestreams)
=> Publish Form: More specific title for edit, refactor

app/src/main/java/com/odysee/app/MainActivity.java, app/src/main/java/com/odysee/app/tasks/wallet/LoadSharedUserStateTask.java, app/src/main/java/com/odysee/app/tasks/wallet/SaveSharedUserStateTask.java
The channel which user wants to use for interactions is only locally stored
The channel selection is synchronized with the one user has set on the web interface and the web interface setting will be updated when selection changes on Odysee Android
=> Sync default channel name selection

app/src/main/java/com/odysee/app/GoLiveActivity.java, app/src/main/java/com/odysee/app/MainActivity.java, app/src/main/java/com/odysee/app/adapter/ReplaysPagerAdapter.java, app/src/main/java/com/odysee/app/model/LivestreamReplay.java, app/src/main/java/com/odysee/app/tasks/LivestreamReplaysResultHandler.java, app/src/main/java/com/odysee/app/tasks/LivestreamReplaysTask.java, app/src/main/java/com/odysee/app/tasks/claim/PublishClaimTask.java, app/src/main/java/com/odysee/app/tasks/claim/ReplayPublishTask.java, app/src/main/java/com/odysee/app/tasks/claim/TusPublishTask.java, app/src/main/java/com/odysee/app/ui/publish/GoLiveFormFragment.java, app/src/main/java/com/odysee/app/ui/publish/LivestreamsFragment.java, app/src/main/java/com/odysee/app/ui/publish/PublishesFragment.java, app/src/main/java/com/odysee/app/ui/publish/ReplaysPageFragment.java, app/src/main/java/com/odysee/app/utils/Helper.java, app/src/main/res/drawable/ic_sync.xml, app/src/main/res/layout/activity_go_live.xml, app/src/main/res/layout/card_livestream_replay.xml, app/src/main/res/layout/fragment_go_live_form.xml, app/src/main/res/layout/fragment_livestreams.xml, app/src/main/res/layout/fragment_replays_page.xml, app/src/main/res/layout/popup_user.xml, app/src/main/res/menu/menu_upload.xml, app/src/main/res/values/strings.xml
UX flow:
- Clicking the Upload button shows menu to pick Upload or Go Live
- Create livestreams with form like publishing
- Choose New Livestream or Upload Replay Replays shown in pages of 4 like on odysee.com
- Choose Anytime or Scheduled Time stream
- Clicking the Create button goes to livestreams dashboard (also accessible from user menu)
- Livestreams dashboard shows stream server and stream key, with button to copy
- Dashboard waits for created claim to finish confirming then enables Start Streaming button
- Clicking Start Streaming goes to activity that streams with HaishinKit
- Streaming activity sets `FLAG_KEEP_SCREEN_ON` in `onCreate` instead of when streaming starts. Also removes flag only `onDestroy`.
Changes of note:
- There are now 3 publish tasks:
- `PublishClaimTask` uses …
=> Match Livestreaming UX flow to odysee.com

.github/issue_template.md
Link is `chat.lbry.com`, which goes to the LBRY Discord
Use `chat.odysee.com` link, which goes to the Odysee Discord
=> issue_template: use correct chat link

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
When newPlayerCreated is set to true, streaming url is refetched and playback is restarted.
Also call setPlayer(null) in setPlayerForPlayerView. Without this playback freezes when returning from picture in picture.
Fix: #356
Playback restarts when going from mini player -> main player.
Playback freezes when returning from picture in picture.
Playback doesn't restart, doesn't freeze.
=> player: don't set newPlayerCreated when playerManager initialized

app/src/main/java/com/odysee/app/MainActivity.java, app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
Issue Number:
#369
For all Android versions, the quality depending on current network is only checked on start of the playback. This means that if user disconnects from a Wifi and connects to cellular, playback will remain at the default Unmetered quality setting.
From Android 7, Start playback quality will be set depending on current network type, but it will be changed accordingly as connectivity changes.
Some indentation has also been changed.
On isMetered() method, in order to see if there is no default connection, code branches depending on Android device OS version. Currently Odysee Android runs from Android Lollipop (API Level 21). getActiveNetworkInfo() is deprecated since Android Q (API …
=> Make playback quality reactive to current network connection

app/src/main/java/com/odysee/app/MainActivity.java
Issue Number:
#359
On devices running up to Android 11, a splash screen is displayed in a forced portrait orientation. From Android 12 the splash screen is displayed by the OS. This causes to keep tghe screen orientation locked into portrait mode although the custom splash screen is not displayed by the app.
From Android 12, the screen is unlocked to current orientation.
Android OS still shows the activity in a locked portrait mode for a few seconds. This PR unlocks it at the earliest moment on code. Trying to move the setRequestedOrientation a few lines before will not fix the issue.
=> Unlock screen rotation from API Level 31 devices

app/src/main/java/com/odysee/app/ui/other/BlockedAndMutedFragment.java
If one of your channels doesn't have any blocked channels, an error "missing blocked_channels key from json response" is thrown and blocked channels aren't listed.
(Un)blocking/(un)muting channels doesn't work.
Just skip single channel if it has no blocked channels instead of throwing an error and stopping checking on all channels.
Don't get signing_channel on claims to unblock/unmute as only channels can be blocked/muted so there's no file claims in the adapter.
Fix inverted and broken logic in context menu actions.
=> blocked & muted view: fix listing blocked and blocking/unblocking

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
Instead only hide it when playing another video/viewing content.
Update mini player bottom margins when starting file view fragment.
Mini player disappears (but video still plays) when opening another claim.
Only hide mini player when starting playback of another file.
=> file view: don't hide global player

app/src/main/java/com/odysee/app/MainActivity.java, app/src/main/java/com/odysee/app/adapter/ClaimListAdapter.java, app/src/main/java/com/odysee/app/ui/channel/ChannelContentFragment.java, app/src/main/java/com/odysee/app/ui/findcontent/AllContentFragment.java, app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java, app/src/main/java/com/odysee/app/ui/findcontent/SearchFragment.java, app/src/main/java/com/odysee/app/ui/library/PlaylistFragment.java, app/src/main/java/com/odysee/app/ui/other/BlockedAndMutedFragment.java, app/src/main/res/menu/menu_stream.xml
Currently, although all context menu actions are shown when opening the context menu on claims on any screen, for most screens the actions don't do anything. Implement the functionality for all screens.
In ClaimListAdapter, remove the longClickForContextMenu flag and always set currentPosition to the item's absolute position in the adapter when a long press occurs. In the context menu listeners, use getCurrentPosition() instead of getPosition() as the latter doesn't return the correct value on a long press.
On the search page, check if a claim is a channel, and if so don't attempt to get its signing channel when blocking/muting.
=> claim context menu: add Report action, implement handlers on all screens

app/src/main/java/com/odysee/app/callable/GetAllLivestreams.java, app/src/main/java/com/odysee/app/ui/findcontent/AllContentFragment.java
Active livestreams are shown on each category except on the Rabbit Hole one
Livestreams are also shown on Rabbit Hole category
=> Show livestreams also for Rabbit Hole category

app/src/main/java/com/odysee/app/ui/publish/GoLiveFormFragment.java, app/src/main/java/com/odysee/app/ui/publish/PublishFormFragment.java
Always set channel from claim even after first load from claim data.
Expected to show "Create a channel" and Anonymous, but they're not
because the ClaimListTask which later calls the method to populate with
placeholder claims fails.
Remove code for showing channel creator from enableChannelSpinner(),
it's already handled in the spinner onItemSelectedListener.
Channel creator shown when turning off then on screen while editing claim.
If account has no channels, going live doesn't show the channel creator and channel spinner has no values, when there should be a "Create a channel" placeholder.
=> Publish/Go Live form fixes

app/src/foss/java/com/odysee/app/utils/CastHelper.java, app/src/full/java/com/odysee/app/utils/CastHelper.java, app/src/main/java/com/odysee/app/MainActivity.java
There is no custom web receiver app so casting is only useful when playing a video.
Cast button introductory overlay is the first thing users see when first opening the app.
Cast button is only visible within video player.
=> chromecast: remove app bar cast button and introductory overlay

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
Navigating away and going back to same claim makes global player show.
Hide global player if resuming with same claim.
=> file view: hide global player if continuing already playing claim

app/src/main/AndroidManifest.xml
Fix "no camera app available to record videos on this device" error.
<details>
<summary>Previous debugging instructions (ignore)</summary>
@tzarebczan please run this (Click Upload then click record, ignore the file loading for now) and either filter for `PublishDebug` in the logcat in Android Studio or run `adb logcat` and filter for lines with `PublishDebug`.
Here's what I get:
```
11-04 16:51:59.357  7097  7097 D PublishDebug: Checking camera permission
11-04 16:51:59.358  7097  7097 D PublishDebug: No camera permission, requesting...
11-04 16:52:04.845  7097  7097 D PublishDebug: About to record (call requestVideoCapture)
11-04 16:52:04.845  7097  7097 D PublishDebug: Requesting video capture
11-04 16:52:04.847  7097  7097 D PublishDebug: Successfully got response from resolveActivity …
```
=> manifest: add <queries> for VIDEO_CAPTURE intent

app/src/main/java/com/odysee/app/ui/findcontent/AllContentFragment.java
Issue Number: #406 (partial)
Livestreams on Home page seems randomnly sorted
They are now sorted by its viewers count
=> Sort active livestreams on categories by descending viewers count

app/src/main/java/com/odysee/app/MainActivity.java, app/src/main/java/com/odysee/app/ui/publish/PublishFragment.java
App could crash when calling some methods not available to prior Android API Levels
A check is implemented to avoid the crash
=> Fix some possible MANAGE_EXTERNAL_STORAGE crashes

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
This reverts the orientation lock (preventing the player from leaving fullscreen) added in
https://github.com/lbryio/lbry-android/commit/540a8412.
Player doesn't exit fullscreen when rotating phone, orientation locked in landscape when player is in fullscreen.
Remove orientation lock, automatically exit fullscreen when rotating to portrait.
I tested this with the situation I'm assuming was described in https://github.com/lbryio/lbry-android/commit/540a8412, i.e. going to/from the global PiP player when in fullscreen mode.
=> file view player: auto exit fullscreen when switching to portrait

app/src/main/java/com/odysee/app/MainActivity.java, app/src/main/java/com/odysee/app/ui/channel/ChannelFragment.java
Executors.newSingleThreadExecutor() creates a new executor, which is an expensive task
This usages have been replaced by the executor which application object creates on the first request.
=> Replace some more newSingleThreadExeutor usages

app/build.gradle
Desugaring allows for Java classes not defined in older Android versions to be available
. Currently, the Instant Java class is used on the project but this was not defined until Android API Level 26.
This PR adds a few comments to build.gradle for when minimum SDK version changes to 26 so whoever makes that change, disables desugaring.
Also, desugaring library versions 1.2 needs a newer AGP than the one Odysee Android is using. Gradle is flaging 1.1.5 as an old one. This PR is also adding a comment so noone loses its time trying to update that version, as it won't build until AGP is also upgraded to 7+
=> Add some comments for desugaring library on build.gradle

app/src/full/AndroidManifest.xml, app/src/main/AndroidManifest.xml
Cleaning up
Some permissions are still held although no longer needed since Android API Level 23
The permissions are no longer requested
=> Remove AccountManager permissions which are no longer needed

app/src/main/java/com/odysee/app/SignInActivity.java, app/src/main/res/layout/activity_sign_in.xml
When user tries to sign up for the first time on Odysee Android, an email message is sent to the new user. UI updates to show to say user that a message has been sent to the address, but no address is being displayed.
This only happens for new email addresses. If user tries to sign in with an existing user account, the address is shown as expected.
User sees to which address the message has been sent. This way it is possible to edit it if user realizes that the address was wrong, like with a typo for example
Additionally, global executors are being used here instead of newly created ones. I saw the UI problem with the email address while searching for "executor" on the prohect source code.
=> Show sign up verification email address

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java
Miniplayer shown and main player doesn't show video after picking location to download to.
Hide miniplayer, call `setPlayerForPlayerView()` which unsets and sets the PlayerView's player so it shows video.
=> file view: hide mini player and fix player after download picked

app/src/main/java/com/odysee/app/ui/channel/ChannelContentFragment.java, app/src/main/java/com/odysee/app/utils/Lbry.java
Fix: #421
Claims with `c:unlisted` and/or a release time in the future (future scheduled) are still shown.
Add `c:unlisted` to `not_tags` and add "release time < now()" for `claim_search` calls.
=> claim_search: filter unlisted and future scheduled

app/src/main/java/com/odysee/app/ui/findcontent/FileViewFragment.java, app/src/main/res/layout/fragment_file_view.xml, app/src/main/res/values/strings.xml
If content is neither playable or viewable, show unsupported content view with button to download the file.
Shut down scheduler used for observing download progress on error or manual abort. This fixes error/success toasts being repeatedly shown. (To get the success toast to repeatedly show, start a download, abort it, then download again).
Also set downloadInProgress to false after download completes successfully.
=> file view: show unsupported content view, fix download toasts

app/build.gradle
This PR changes the way Google Play Services related Gradle tasks are disabled on Foss build variants. This change was made because of a Linter suggestion.
Additionally, Glide processor has been finally updated and moved so it is now closer to the Glide dependency.
=> Change the way Play Services tasks are disabled (Linter suggestion)

app/src/main/java/com/odysee/app/MainActivity.java
In some situations, app crashes after user has pressed device's back button
App will not crash
The fix consists in moving title and "balance and tools layout" to a conditional branch. Those views are part of the toolbar which, from the OS point-of-view, is the action bar. If there is no action bar at that point, those views cannot be accessed, causing the crash.
=> Fix crash when back-button is pressed
